name: Automatic File Creation

on:
  schedule:
    - cron: "0 3,15 * * *"
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: "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"

      - name: Create new file
        run: |
          count=1

          while [ -f "file$count.txt" ]
          do
            ((count++))
          done

          touch "file$count.txt"

          echo "file$count.txt created successfully"

      - name: Commit and Push
        run: |
          git config user.name "Soumyadeepjana1"
          git config user.email "soumyadeepjana368@gmail.com"

          git add .
          git commit -m "Auto create new file" || echo "Nothing to commit"
          git push

